apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitcoin.fullname" . }}
  labels:
    {{- include "bitcoin.labels" . | nindent 4 }}
data:
  bitcoin.conf: |-
    server=1
    printtoconsole=1
    rpcuser={{ .Values.rpcuser }}
    rpcpassword={{ .Values.rpcpassword }}
    rpcallowip=0.0.0.0/0    
